using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;

namespace KengaCAD
{
    /// <summary>Постпроцессоры: экспорт траектории в форматы контроллеров роботов.</summary>
    public static class Postprocessors
    {
        public static bool ExportKukaKrl(IReadOnlyList<TrajectoryPoint> points, string filePath,
            double speedMmS = 100, string? programName = null)
        {
            if (PostprocessorEngine.TryExport("kuka_krl", points, filePath, speedMmS)) return true;
            return ExportKukaKrlFallback(points, filePath, speedMmS, programName);
        }

        private static bool ExportKukaKrlFallback(IReadOnlyList<TrajectoryPoint> points, string filePath,
            double speedMmS = 100, string? programName = null)
        {
            var prev = CultureInfo.CurrentCulture;
            CultureInfo.CurrentCulture = CultureInfo.InvariantCulture;
            try
            {
            if (points == null || points.Count == 0) return false;
            programName ??= "KengaCAD_Trajectory";
            double vel = speedMmS / 1000.0;
            var sb = new StringBuilder();
            sb.AppendLine($"DEF {programName}()");
            sb.AppendLine("  ; Generated by KengaCAD Professional");
            sb.AppendLine($"  ; Points: {points.Count}");
            sb.AppendLine($"  $VEL.CP = {vel:F3}");
            sb.AppendLine($"  $VEL.CP = {vel:F3}");
            sb.AppendLine("  $TOOL = TOOL_DATA[1]");
            sb.AppendLine("  $BASE = BASE_DATA[0]");
            sb.AppendLine();
            foreach (var pt in points)
                sb.AppendLine($"  LIN {{X {pt.X:F3}, Y {pt.Y:F3}, Z {pt.Z:F3}, A {pt.Rz:F3}, B {pt.Ry:F3}, C {pt.Rx:F3}}} C_DIS");
            sb.AppendLine("  ; End trajectory");
            sb.AppendLine("END");
            try
            {
                File.WriteAllText(filePath, sb.ToString(), Encoding.UTF8);
                return true;
            }
            catch { return false; }
            }
            finally { CultureInfo.CurrentCulture = prev; }
        }

        public static bool ExportAbbRapid(IReadOnlyList<TrajectoryPoint> points, string filePath,
            double speedMmS = 100, string? moduleName = null, string? toolName = null)
        {
            if (PostprocessorEngine.TryExport("abb_rapid", points, filePath, speedMmS)) return true;
            return ExportAbbRapidFallback(points, filePath, speedMmS, moduleName, toolName);
        }

        private static bool ExportAbbRapidFallback(IReadOnlyList<TrajectoryPoint> points, string filePath,
            double speedMmS = 100, string? moduleName = null, string? toolName = null)
        {
            if (points == null || points.Count == 0) return false;
            moduleName ??= "KengaCAD_Trajectory";
            toolName ??= "tool0";
            var sb = new StringBuilder();
            sb.AppendLine($"MODULE {moduleName}");
            sb.AppendLine("  ! Generated by KengaCAD Professional");
            sb.AppendLine($"  ! Points: {points.Count}");
            sb.AppendLine($"  ! Speed: {speedMmS} mm/s");
            sb.AppendLine();
            sb.AppendLine($"  PERS tooldata {toolName} := [TRUE,[[0,0,0],[1,0,0,0]],[0.001,[0,0,0.001],[1,0,0,0],0,0,0]];");
            sb.AppendLine();
            sb.AppendLine("  PROC main()");
            sb.AppendLine("    ConfJ \\Off;");
            sb.AppendLine("    ConfL \\Off;");
            int v = (int)Math.Round(speedMmS);
            foreach (var pt in points)
            {
                var q = pt.Quaternion;
                sb.AppendLine($"    MoveL [[{pt.X:F3},{pt.Y:F3},{pt.Z:F3}],[{q.Q1:F6},{q.Q2:F6},{q.Q3:F6},{q.Q4:F6}],[0,0,0,0],[9E+09,9E+09,9E+09,9E+09,9E+09,9E+09]], v{v}, fine, {toolName};");
            }
            sb.AppendLine("  ENDPROC");
            sb.AppendLine("ENDMODULE");
            try
            {
                File.WriteAllText(filePath, sb.ToString(), Encoding.UTF8);
                return true;
            }
            catch { return false; }
        }

        public static bool ExportFanucTp(IReadOnlyList<TrajectoryPoint> points, string filePath,
            double speedMmS = 100, string? programName = null, int utoolNum = 1, int uframeNum = 0)
        {
            if (PostprocessorEngine.TryExport("fanuc_tp", points, filePath, speedMmS)) return true;
            return ExportFanucTpFallback(points, filePath, speedMmS, programName, utoolNum, uframeNum);
        }

        private static bool ExportFanucTpFallback(IReadOnlyList<TrajectoryPoint> points, string filePath,
            double speedMmS = 100, string? programName = null, int utoolNum = 1, int uframeNum = 0)
        {
            if (points == null || points.Count == 0) return false;
            programName ??= "KengaCAD_TRAJ";
            var sb = new StringBuilder();
            sb.AppendLine($"/PROG  {programName}");
            sb.AppendLine("/ATTR");
            sb.AppendLine("OWNER       = MNEDITOR;");
            sb.AppendLine("COMMENT     = \"Generated by KengaCAD Professional\";");
            sb.AppendLine("PROG_SIZE   = 0;");
            sb.AppendLine("CREATE      = DATE UNKNOWN  TIME UNKNOWN;");
            sb.AppendLine("MODIFIED    = DATE UNKNOWN  TIME UNKNOWN;");
            sb.AppendLine("FILE_NAME   = ;");
            sb.AppendLine("VERSION     = 0;");
            sb.AppendLine($"LINE_COUNT  = {points.Count};");
            sb.AppendLine("MEMORY_SIZE = 0;");
            sb.AppendLine("PROTECT     = READ_WRITE;");
            sb.AppendLine("TCD:  STACK_SIZE    = 0,");
            sb.AppendLine("      TASK_PRIORITY = 50,");
            sb.AppendLine("      TIME_SLICE    = 0,");
            sb.AppendLine("      BUSY_LAMP_OFF = 0,");
            sb.AppendLine("      ABORT_REQUEST = 0,");
            sb.AppendLine("      PAUSE_REQUEST = 0;");
            sb.AppendLine("DEFAULT_GROUP  = 1,*,*,*,*;");
            sb.AppendLine("CONTROL_CODE   = 00000000 00000000;");
            sb.AppendLine("/APPL");
            sb.AppendLine("/MN");
            sb.AppendLine($"   1:  UTOOL_NUM={utoolNum} ;");
            sb.AppendLine($"   2:  UFRAME_NUM={uframeNum} ;");
            int idx = 3;
            foreach (var pt in points)
            {
                sb.AppendLine($"   {idx}:L P[{idx - 2}:point{idx - 2}] {speedMmS}mm/sec FINE    ;");
                idx++;
            }
            sb.AppendLine("/POS");
            for (int i = 0; i < points.Count; i++)
            {
                var pt = points[i];
                sb.AppendLine($"P[{i + 1}:\"point{i + 1}\"]{{");
                sb.AppendLine("  GP1:");
                sb.AppendLine($"  UF : {uframeNum}, UT : {utoolNum},");
                sb.AppendLine($"  X = {pt.X:F3}  mm, Y = {pt.Y:F3}  mm, Z = {pt.Z:F3}  mm,");
                sb.AppendLine($"  W = {pt.Rx:F3}  deg, P = {pt.Ry:F3}  deg, R = {pt.Rz:F3}  deg");
                sb.AppendLine("};");
            }
            sb.AppendLine("/END");
            try
            {
                File.WriteAllText(filePath, sb.ToString(), Encoding.UTF8);
                return true;
            }
            catch { return false; }
        }

        public static bool ExportYaskawaInform(IReadOnlyList<TrajectoryPoint> points, string filePath,
            double speedMmS = 100, string? jobName = null)
        {
            if (PostprocessorEngine.TryExport("yaskawa_inform", points, filePath, speedMmS)) return true;
            return ExportYaskawaInformFallback(points, filePath, speedMmS, jobName);
        }

        private static bool ExportYaskawaInformFallback(IReadOnlyList<TrajectoryPoint> points, string filePath,
            double speedMmS = 100, string? jobName = null)
        {
            if (points == null || points.Count == 0) return false;
            jobName ??= "KENGACAD_TRAJ";
            string date = DateTime.Now.ToString("yyyy/MM/dd HH:mm");
            var sb = new StringBuilder();
            sb.AppendLine("/JOB");
            sb.AppendLine($"//NAME {jobName}");
            sb.AppendLine("//POS");
            sb.AppendLine($"///NPOS {points.Count},0,0,0,0,0,0,0");
            sb.AppendLine("///TOOL 0");
            sb.AppendLine("///POSTYPE PULSE");
            sb.AppendLine("///PULSE");
            for (int i = 0; i < points.Count; i++)
            {
                var pt = points[i];
                sb.AppendLine($"C{i:D5}={pt.X:F3},{pt.Y:F3},{pt.Z:F3},{pt.Rx:F3},{pt.Ry:F3},{pt.Rz:F3}");
            }
            sb.AppendLine("//INST");
            sb.AppendLine($"///DATE {date}");
            sb.AppendLine("///ATTR SC,RW");
            sb.AppendLine("///GROUP1 RB1");
            sb.AppendLine("///COMM Generated by KengaCAD Professional");
            sb.AppendLine("NOP");
            for (int i = 0; i < points.Count; i++)
                sb.AppendLine($"MOVL C{i:D5} V={speedMmS:F1}");
            sb.AppendLine("END");
            sb.AppendLine("/END");
            try
            {
                File.WriteAllText(filePath, sb.ToString(), Encoding.UTF8);
                return true;
            }
            catch { return false; }
        }

        public static bool ExportUrScript(IReadOnlyList<TrajectoryPoint> points, string filePath,
            double speedMs = 0.1, double accel = 1.2, string? programName = null)
        {
            if (PostprocessorEngine.TryExport("ur_script", points, filePath)) return true;
            return ExportUrScriptFallback(points, filePath, speedMs, accel, programName);
        }

        private static bool ExportUrScriptFallback(IReadOnlyList<TrajectoryPoint> points, string filePath,
            double speedMs = 0.1, double accel = 1.2, string? programName = null)
        {
            if (points == null || points.Count == 0) return false;
            programName ??= "KengaCAD_Trajectory";
            var sb = new StringBuilder();
            sb.AppendLine("# Generated by KengaCAD Professional");
            sb.AppendLine($"# Program: {programName}");
            sb.AppendLine($"# Points: {points.Count}");
            sb.AppendLine($"# Speed: {speedMs} m/s, Accel: {accel} m/s^2");
            sb.AppendLine();
            sb.AppendLine("def " + programName + "():");
            sb.AppendLine("  set_tcp(p[0.0, 0.0, 0.0, 0.0, 0.0, 0.0])");
            sb.AppendLine();
            foreach (var pt in points)
            {
                double x = pt.X / 1000.0, y = pt.Y / 1000.0, z = pt.Z / 1000.0;
                sb.AppendLine($"  movel(p[{x:F6}, {y:F6}, {z:F6}, {pt.Rx:F4}, {pt.Ry:F4}, {pt.Rz:F4}], a={accel}, v={speedMs})");
            }
            sb.AppendLine("  textmsg(\"" + programName + " completed\")");
            sb.AppendLine("end");
            try
            {
                File.WriteAllText(filePath, sb.ToString(), Encoding.UTF8);
                return true;
            }
            catch { return false; }
        }

        public static bool ExportGCode(IReadOnlyList<TrajectoryPoint> points, string filePath, double feedMmMin = 3000)
        {
            if (points == null || points.Count == 0) return false;
            var sb = new StringBuilder();
            sb.AppendLine("; KengaCAD Professional - G-code trajectory");
            sb.AppendLine("G90 G21");
            foreach (var pt in points)
                sb.AppendLine($"G1 X{pt.X:F3} Y{pt.Y:F3} Z{pt.Z:F3} F{feedMmMin:F0}");
            sb.AppendLine("M30");
            try
            {
                File.WriteAllText(filePath, sb.ToString(), Encoding.UTF8);
                return true;
            }
            catch { return false; }
        }
    }
}
